name: Update Language Statistics

on:
  schedule: # run automatically every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch: # allows to manually run the job at any time
  push: # run on every push on the master branch
    branches:
      - main


permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: StefVuck/Github-Language-Stats@v1.2.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "leaderboard"
          output_path: "stats"
